name: Latest Blog Posts

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:     # Allows manual triggering

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://mdtanveer.com/rss.xml"
          max_post_count: 5
          readme_path: "./README.md"
          template: "* [$title]($url) - $date"
          committer_username: "github-actions[bot]"
          committer_email: "41898282+github-actions[bot]@users.noreply.github.com"
